### ISSUE TITLE
Resource allocation

### ISSUE THREAD

**Issue by herzog31** [hlxsites/asprey#3]
Allocate engineers to project:

- [x] AEM VIP
    - [x] 1 Project lead (Mark)
    - [x] 4 Engineers (3 experienced, 1 beginner) (Hannes, Luca, JC, + ?)
- [x] Commerce (1 Engineer each)
    - [x] Catalog service / PDP widget (Sandra, Andy, Patrick)
    - [x] Checkout (Olena, Stephen, Martino, Patrick)
    - [x] Livesearch / Search widget / Recommendations / PLP (Kathleen, Arjun, Ani, Irene)
- [x] Asprey / MRM
    - [x] Authoring, Block development, martech (Aidan, Jonathan, Andrew)
    - [x] PWA + CDN (Stefan (MRM))
    - [x] Commerce (Aishwarya)
