### ISSUE TITLE
Kickoff Meeting

### ISSUE THREAD

**Issue by herzog31** [hlxsites/asprey#4]
## Participants
- Asprey (Aidan, Jonathan, Andrew, Aishwarya, Alisha)
- MRM (Stefan, Larissa, Joe)
- Commerce (Sandra, Andy, Patrick, Olena, Stephen, Martino, Kathleen, Arjun, Ani, Irene)
- AEM (Mark, Hannes, Luca, JC, Cosmin)

## Agenda
- [x] @herzog31 create action items from open requirements in this ticket.
- Introduce people, responsibilities
- Project scope
    - Migrate asprey.com to Franklin
    - Currently using AEM + CIF Add-on + Checkout/cart based on PWA Studio, Adyen payments
    - Content and catalog pages will be migrated to Sharepoint (Word + Excel)
    - Account, cart and checkout will be copied over as-is
    - _Phase 2 (parallel):_ Usage of Commerce drop-ins
    - **Goals:** Lighthouse 100, better authoring experience, go-live before blackout period
- Confirm timeline and go-live date
    - Currently planned for October 31
    - 7 weeks left, estimated 10-12 weeks
- Confirm roadmap and owners, define champions for topics:
    - Content & authoring: Jonathan
    - Commerce: Aishwarya
    - CDN: Aidan
    - CIF PWA implementation (account, cart, checkout): Larissa to find right person
    - Marketing technology (tag management, analytics, etc.): Jonathan
- Find slot for regular meetings (weekly)
    - [x] @herzog31 to schedule meeting around the same timeslot as kick-off
    - Communication via Slack
    - Issue tracking via GitHub
- Additional requirements and dependencies
    - Everyone to have access to GitHub
    - Franklin
        - #51
        - #52
        - #53
        - #54
        - #1 
        - #55
        - #27 
    - Catalog Service & Live Search
        - Once sync is done, validate data 
    - Checkout
        - [x] Commerce upgrade to 2.4.7
        - [ ] Define checkout requirements
        - [x] Identify stakeholders on checkout + PDP functionality (Aishwarya)

![image](https://github.com/hlxsites/asprey/assets/4084418/0bda42c0-4b2a-4215-a246-e11c5cfe5076)
